version: '3.5'
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.5.9
#    command: 
    restart: always
    user: root
    environment:
      TZ: Asia/Shanghai
    ports:
      - 2181:2181
    volumes:
      - ./volume/data:/data
      - ./volume/datalog:/datalog


