version: '3.5'
services:
  rocketmq-server:
    container_name: rocketmq-server
    image: rocketmqinc/rocketmq:4.4.0
    command: 'sh mqnamesrv'
    restart: always
    user: root
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 9876:9876
    volume:
      - ./volume/nameserver.logs:/home/rocketmq/logs
      - ./volume/nameserver.store:/home/rocketmq/store

  rocketmq-broker:
    container_name: rocketmq-broker
    image: rocketmqinc/rocketmq:4.4.0
    command: 'sh mqbroker -n rocketmq-server:9876 -c ../conf/broker.conf'
    restart: always
    user: root
    environment:
      TZ: Asia/Shanghai
      JAVA_HOME: /usr/lib/jvm/jre
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volume:
      - ./volume/broker.logs:~/logs
      - ./volume/broker.store:~/store
      - ./volume/conf/broker.conf:/opt/rocketmq-4.4.0/conf/broker.conf
    depends_on:
      - rocketmq-server

  rocketmq-console:
    container_name: rocketmq-console
    image: styletang/rocketmq-console-ng:1.0.0
    restart: always
    user: root
    environment:
      TZ: Asia/Shanghai
      JAVA_OPTS: '-Dlogging.level.root=info -Drocketmq.namesrv.addr=rocketmq-server:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false'
    ports:
      - 8087:8080
    depends_on:
      - rocketmq-server
