version: '3.5'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:6.5.0
    restart: always
    user: root
    environment:
      TZ: Asia/Shanghai
    ports: 
      - 3000:3000
#    volumes:
#    - .volumes/elasticsearch/data:/usr/share/elasticsearch/data
    
