version: '3.5'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.11-management
#    command: 
    restart: always
    user: root
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 5672:5672
      - 15672:15672
#    volumes:
#      - ./volume/data:/usr/share/elasticsearch/data
#      - ./volume/plugins:/usr/share/elasticsearch/plugins
