version: '3.5'
services:
  mysql:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-use-native-aio=0
    restart: always
    user: root
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33060:3306
    volumes:
      - ./volume/data:/var/lib/mysql
