version: '3.5'
services:
  kafka-zookeeper:
    container_name: kafka-zookeeper
    image: zookeeper:3.5.9
    #    command:
    restart: always
    user: zookeeper
    environment:
      TZ: Asia/Shanghai
    ports:
      - 2181:2181
    volumes:
      - ./volume/zk.data:/data
      - ./volume/zk.datalog:/datalog

  kafka-broker1:
    container_name: kafka-broker1
    image: bitnami/kafka:2.8.1
    restart: always
    #    user: root
    environment:
      TZ: Asia/Shanghai
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
    #  KAFKA_CFG_LISTENERS: 'PLAINTEXT://0.0.0.0:9092'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://33.1.0.12:19092'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      JMX_PORT: 19999
    ports:
      - 19092:9092
      - 19999:19999
    volumes:
      - ./volume/broker-1.data:/bitnami/kafka/data
    depends_on:
      - kafka-zookeeper


  kafka-broker2:
    container_name: kafka-broker2
    image: bitnami/kafka:2.8.1
    restart: always
    #    user: root
    environment:
      TZ: Asia/Shanghai
      KAFKA_BROKER_ID: 2
      KAFKA_CFG_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
    #  KAFKA_CFG_LISTENERS: 'PLAINTEXT://0.0.0.0:9092'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://33.1.0.12:29092'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      JMX_PORT: 29999
    ports:
      - 29092:9092
      - 29999:29999
    volumes:
      - ./volume/broker-2.data:/bitnami/kafka/data
    depends_on:
      - kafka-zookeeper

